### ISSUE TITLE
[Error] certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by xpirad** [tongyuantongyu/WebNovelCrawler#2] opened 2019-12-28 11:06 UTC
Output :
=======================================================
[Initial] Input novel id here: 1177354054881165840
[Main Thread] Fetching Metadata...
[Main Thread] Fetching Pages...
.\kakuyomu.py:96: DeprecationWarning: 'with await lock' is deprecated use 'async with lock' instead
  with await semaphore:
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001DABE9B20F0>
transport: <_SelectorSocketTransport fd=852 read=polling write=<idle, bufsize=0>>
=======================================================

Hi, thanks for writing this tool.
May i ask how to solve this issue? 
I'm using Python 3.7 on Windows 10

**Comment by tongyuantongyu** [comment] 2020-01-16 06:34
This is a SSL issue. Some tests are required.
1. Just retry. Most network related issues are temporary.
2. Check if you can open Kakuyomu's website using your browser, without any certificate-related warning?
3. Try if this minified test script works:
```python
import asyncio
import aiohttp

async def get():
     async with aiohttp.ClientSession() as session:
          async with session.get("https://kakuyomu.jp") as response:
              print(response)

asyncio.run(get())
```
4. Maybe an output of command ```pip list``` helps if the issue is still present.

**Comment by tongyuantongyu** [comment] 2021-01-18 13:47
Reporter didn't respond for a long time, so I'm closing this. If the issue is still present, please re-open it.

**Closed as completed by tongyuantongyu** 2021-01-18 13:47 UTC
